name: MoneyMake
version: '1.2'
main: smitedreal.moneyMake.MoneyMake
api-version: '1.21'
authors: [ SmiteGee ]
commands:
  sell:
    description: Sell gold stuff for in-game money.
    permission-message: You do not have permission to sell items.
